---
- name: Install apt-get preps for fuel
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - git
    - make
    - curl
    - libvirt-bin
    - libpq-dev
    - qemu-kvm
    - qemu-system
    - tightvncserver
    - virt-manager
    - sshpass
    - fuseiso
    - genisoimage
    - blackbox
    - xterm
    - python-pip
    - python-git
    - python-dev
    - python-oslo.config
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - expect
    - python-netaddr
    - p7zip-full

- name: Install pip preps for fuel
  pip: name={{item}} extra_args="--upgrade"
  with_items:
    - pip
    - GitPython
    - pyyaml
    - netaddr
    - paramiko
    - lxml
    - scp
    - pycrypto
    - ecdsa
    - debtcollector
    - netifaces
    - enum

# Should also work
#- name: Checkout fuel repo
#  git:
#    repo: https://git.opnfv.org/fuel
#    dest: /fuel
#    version: stable/colorado
#    clone: yes

- name: Copy Fuel Repo
  unarchive:
    src: ./fuel-files/fuel.tar.gz
    dest: /
    remote_src: no

- name: Download OPNFV Colorado
  get_url:
    url: http://artifacts.opnfv.org/fuel/colorado/opnfv-colorado.2.0.iso
    dest: /fuel/opnfv-colorado.iso

- name: Creates lab directory
  file: path={{item}} state=directory
  with_items:
    - /fuel/deploy/config/labs/devel-pipeline/telematik-kit
    - /fuel/deploy/images

- name: Copy lab folder
  shell: cp -r /fuel/deploy/config/labs/devel-pipeline/elx/* /fuel/deploy/config/labs/devel-pipeline/telematik-kit

- name: Copy dha.yaml
  copy:
    src: ./fuel-files/dha.yaml
    dest: /fuel/deploy/config/labs/devel-pipeline/telematik-kit/fuel/config/dha.yaml
    force: true

#[WARNING]: Consider using template or lineinfile module rather than running sed
#TODO Use lineinfile
- name: Adjust qemu config add root user
  shell: sed -i 's/#user = "root"/user = "root"/g' /etc/libvirt/qemu.conf

- name: Adjust qemu config add root group
  shell: sed -i 's/#group = "root"/group = "root"/g' /etc/libvirt/qemu.conf

- name: Restart libvirt
  service:
    name: libvirt-bin
    state: restarted

- name: Execute fuel
  shell: bash ./deploy.sh -b file:///fuel/deploy/config/ -l devel-pipeline -p telematik-kit -s no-ha_odl-l2_sfc_heat_ceilometer_scenario.yaml -i file:///fuel/opnfv-colorado.iso
  args:
    chdir: /fuel/ci
