---
- name: Install apt-get preps for fuel
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - git
    - make
    - curl
    - libvirt-bin
    - libpq-dev
    - qemu-kvm
    - qemu-system
    - tightvncserver
    - virt-manager
    - sshpass
    - fuseiso
    - genisoimage
    - blackbox
    - xterm
    - python-pip
    - python-git
    - python-dev
    - python-oslo.config
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - expect
    - python-netaddr
    - p7zip-full

- name: Install pip preps for fuel
  pip: name={{item}} extra_args="--upgrade"
  with_items:
    - pip
    - GitPython
    - pyyaml
    - netaddr
    - paramiko
    - lxml
    - scp
    - pycrypto
    - ecdsa
    - debtcollector
    - netifaces
    - enum

- name: Checkout fuel repo
  git:
    repo: https://git.opnfv.org/fuel
    dest: /fuel
    version: stable/colorado
    clone: yes
  when: not use_local

- name: Copy Fuel Repo
  unarchive:
    src: ./fuel-files/fuel.tar.gz
    dest: /
    remote_src: no
  when: use_local

- name: Download OPNFV Colorado
  get_url:
    url: "{{ fuel_url }}"
    dest: /fuel/opnfv-colorado.iso

- name: Creates lab directory
  file: path={{item}} state=directory
  with_items:
    - /fuel/deploy/config/labs/devel-pipeline/{{ lab_name }}
    - /fuel/deploy/images

- name: Copy lab folder
  shell: cp -r /fuel/deploy/config/labs/devel-pipeline/elx/* /fuel/deploy/config/labs/devel-pipeline/{{ lab_name }}

- name: Copy dha.yaml
  copy:
    src: ./fuel-files/dha.yaml
    dest: /fuel/deploy/config/labs/devel-pipeline/{{ lab_name }}/fuel/config/dha.yaml
    force: true

- name: Copy dea-pod-override.yaml
  copy:
    src: ./fuel-files/dea-pod-override.yaml
    dest: /fuel/deploy/config/labs/devel-pipeline/{{ lab_name }}/fuel/config/dea-pod-override.yaml
    force: true

- name: Adjust qemu config add root user
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    line: "user = \"root\""

- name: Adjust qemu config add root group
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    line: "group = \"root\""

- name: Restart libvirt
  service:
    name: libvirt-bin
    state: restarted

# -F (only fuel master)
- name: Execute fuel
  shell: bash ./deploy.sh -b file:///fuel/deploy/config/ -l devel-pipeline -p {{ lab_name }} -s {{ scenario }} -i file:///fuel/opnfv-colorado.iso
  args:
    chdir: /fuel/ci
  when: deploy_fuel
